title: Sowmya Maddali
#logo: /assets/img/headshot_circle.png
description: Arlington, VA | (571)-541-8212 | [maddalisowmya@gmail.com](maddalisowmya@gmail.com) | [LinkedIn](https://www.linkedin.com/in/sowmya-maddali-2495b3169/) | [GitHub](https://github.com/sowmyamaddali)
show_downloads: false
theme: jekyll-theme-slate
